"""Archive the audience counters into the Obsidian vault.

Redis holds ninety days and then prunes itself, which is right for a cache and
wrong for a record. This copies each day out before it expires, so the history
outlives both the cache and the repository — the same reason the weekly notes
are mirrored by `sync_vault.py`.

Three things are written, and the order matters:

    Analytics/data/<date>.json   the raw counters, exactly as stored. The
                                 source of truth. Never regenerated from the
                                 notes, only from Redis.
    Analytics/<date>.md          that day, readable, for the graph and search.
    Analytics/Audience Index.md  every day plus all-time totals, derived from
                                 every JSON file present.

Derived files are rebuilt from the JSON on every run, so a change to how a note
reads is one run away from applying to the whole history. The JSON is only ever
written for a day that is still in Redis, and never overwritten with less than
it already has: a day that has aged out of the cache keeps whatever was captured
while it was there.

Idempotent, and safe to run any number of times.

    python scripts/sync_analytics.py [--vault PATH] [--days 90]
"""

from __future__ import annotations

import argparse
import json
import sys
import urllib.error
import urllib.parse
import urllib.request
from collections import Counter
from datetime import date, timedelta
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(REPO / "src"))

from unprompted.run import load_local_env  # noqa: E402

DEFAULT_VAULT = Path.home() / "FenrirVault"
FOLDER = Path("Projects") / "Unprompted" / "Analytics"
STAMP = "type: unprompted-audience"
INDEX_STAMP = "Generated by `scripts/sync_analytics.py`"

PURPOSE_WORD = {
    "live": "answering someone",
    "training": "training / indexing",
    "search": "search crawl",
}
# The composite separator used by lib/analytics.ts. A control character, because
# two agent names contain a space.
PAIR_SEP = "\x00"


# Hosts that are an assistant rather than a website. Mirrors ASSISTANT_HOSTS in
# lib/analytics.ts; short and stable enough that a shared file would cost more
# than it saves, unlike the agent registry which is long and changes.
ASSISTANT_HOSTS = (
    "chatgpt.com", "chat.openai.com", "openai.com", "perplexity.ai", "claude.ai",
    "gemini.google.com", "copilot.microsoft.com", "bing.com", "you.com",
    "phind.com", "poe.com", "duckduckgo.com", "mistral.ai", "chat.mistral.ai",
    "grok.com", "x.ai",
)


def is_assistant(host: str) -> bool:
    return any(host == h or host.endswith(f".{h}") for h in ASSISTANT_HOSTS)


def registry() -> dict[str, dict[str, str]]:
    """Agent metadata, from the same file the site classifies requests with."""
    data = json.loads((REPO / "agents.json").read_text(encoding="utf-8"))
    return {a["name"]: a for a in data["agents"]}


# -- reading redis ------------------------------------------------------------


def fetch_day(url: str, token: str, day: str) -> dict[str, int]:
    """One day's counters, or {} when the key has expired or never existed."""
    key = urllib.parse.quote(f"a:d:{day}", safe="")
    request = urllib.request.Request(
        f"{url}/hgetall/{key}", headers={"Authorization": f"Bearer {token}"}
    )
    try:
        with urllib.request.urlopen(request, timeout=20) as response:
            flat = json.loads(response.read()).get("result") or []
    except (urllib.error.URLError, TimeoutError, ValueError) as exc:
        print(f"  {day}: unreachable ({exc})", file=sys.stderr)
        return {}
    return {flat[i]: int(flat[i + 1]) for i in range(0, len(flat) - 1, 2)}


def split(counters: dict[str, int], kind: str) -> dict[str, int]:
    prefix = f"{kind}:"
    return {k[len(prefix):]: v for k, v in counters.items() if k.startswith(prefix)}


# -- writing the vault --------------------------------------------------------


def write_raw(out_dir: Path, day: str, counters: dict[str, int]) -> bool:
    """Store the day, unless what we have is smaller than what is already there.

    A day drops out of Redis after ninety days and comes back as {}. Writing
    that over a good archive would quietly delete the history this script exists
    to keep, so the archive only ever grows.
    """
    path = out_dir / "data" / f"{day}.json"
    path.parent.mkdir(parents=True, exist_ok=True)

    if path.exists():
        try:
            existing = json.loads(path.read_text(encoding="utf-8"))
        except ValueError:
            existing = {}
        if sum(existing.values()) >= sum(counters.values()):
            return False

    path.write_text(json.dumps(counters, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    return True


def table(rows: dict[str, int], head: tuple[str, str], limit: int = 25) -> list[str]:
    if not rows:
        return ["_Nothing._", ""]
    out = [f"| {head[0]} | {head[1]} |", "|---|---:|"]
    for name, count in sorted(rows.items(), key=lambda kv: -kv[1])[:limit]:
        out.append(f"| {name} | {count} |")
    out.append("")
    return out


def _sentence(purposes: dict[str, int]) -> str:
    """The split, in prose that agrees with itself at one as well as at ten."""
    live, training, search = (purposes.get(k, 0) for k in ("live", "training", "search"))

    def crawls(n: int, kind: str) -> str:
        return f"{n} was a {kind} crawl" if n == 1 else f"{n} were {kind} crawls"

    lead = (
        f"{live} of the agent hits was an assistant"
        if live == 1
        else f"{live} of the agent hits were assistants"
    )
    return (
        f"{lead} reading this page to answer a person. "
        f"{crawls(training, 'training or indexing')}, "
        f"{crawls(search, 'search')}."
    )


def day_note(day: str, counters: dict[str, int], meta: dict[str, dict[str, str]]) -> str:
    agents = split(counters, "g")
    purposes = split(counters, "p")
    totals = split(counters, "t")

    lines = [
        "---",
        STAMP,
        f"date: {day}",
        f"agents: {totals.get('agent', 0)}",
        f"humans: {totals.get('human', 0)}",
        f"answering: {purposes.get('live', 0)}",
        "---",
        "",
        f"# Audience — {day}",
        "",
        f"**{totals.get('agent', 0)} agent hits · {totals.get('human', 0)} human views**",
        "",
        _sentence(purposes),
        "",
        "## Which assistants",
        "",
    ]

    if agents:
        lines += ["| Agent | Vendor | Why | Hits |", "|---|---|---|---:|"]
        for name, count in sorted(agents.items(), key=lambda kv: -kv[1]):
            info = meta.get(name, {})
            why = PURPOSE_WORD.get(info.get("purpose", ""), "—")
            lines.append(f"| {name} | {info.get('vendor', '—')} | {why} | {count} |")
        lines.append("")
    else:
        lines += ["_No agent identified itself._", ""]

    pairs = {k.replace(PAIR_SEP, " → "): v for k, v in split(counters, "gp").items()}
    lines += ["## What the agents read", ""] + table(pairs, ("Agent → page", "Hits"))
    lines += ["## Brands looked up", ""] + table(split(counters, "b"), ("Brand", "Views"))
    lines += ["## Compared against each other", ""] + table(
        split(counters, "m"), ("Pair", "Times")
    )
    lines += ["## Pages people read", ""] + table(split(counters, "v"), ("Page", "Views"))
    lines += ["## Clicks", ""] + table(split(counters, "c"), ("Element", "Clicks"))

    referrers = split(counters, "r")
    assistants = {k: v for k, v in referrers.items() if is_assistant(k)}
    if assistants:
        lines += ["## Arrived from an assistant", ""] + table(
            assistants, ("Assistant", "Visits")
        )
    lines += ["## Came from", ""] + table(referrers, ("Referrer", "Visits"))

    missing = split(counters, "x")
    if missing:
        lines += ["## Asked for, and not here", ""] + table(missing, ("Path", "Times"))

    lines += [
        "---",
        "",
        "Counted by the site itself; agents from the request, people from a beacon.",
        "No cookie, no identifier and no address is stored. A user agent is",
        "self-declared and can be forged, so read these as what the client said it",
        "was rather than as proof.",
        "",
        "Part of [[Projects/Unprompted/MOC|Unprompted]].",
        "",
    ]
    return "\n".join(lines)


def write_index(out_dir: Path, meta: dict[str, dict[str, str]]) -> None:
    """Every archived day, plus all-time totals derived from the raw files."""
    files = sorted((out_dir / "data").glob("*.json"))
    life: Counter[str] = Counter()
    for path in files:
        try:
            for field, count in json.loads(path.read_text(encoding="utf-8")).items():
                life[field] += int(count)
        except (ValueError, TypeError):
            continue

    def of(kind: str) -> dict[str, int]:
        return {k[len(kind) + 1:]: v for k, v in life.items() if k.startswith(f"{kind}:")}

    totals, purposes = of("t"), of("p")
    lines = [
        "---",
        "type: index",
        "---",
        "",
        "# Unprompted, audience",
        "",
        f"All time, across {len(files)} archived day(s).",
        "",
        # One line, deliberately. The ownership check below is a substring test,
        # and wrapping this sentence across two lines meant the stamp never
        # appeared contiguously: the script refused to update its own index.
        f"{INDEX_STAMP} in the Unprompted repository. Edits here are overwritten;",
        "the day notes and `data/` beside them are the record.",
        "",
        f"**{totals.get('agent', 0)} agent hits · {totals.get('human', 0)} human views**",
        "",
        # Same sentence builder as a day note, so the counts agree with their
        # verbs in both places rather than only in one.
        _sentence(purposes).replace("the agent hits", "all agent hits").replace(
            "this page", "a page here"
        ),
        "",
        "## Which assistants, all time",
        "",
    ]

    agents = of("g")
    if agents:
        lines += ["| Agent | Vendor | Why | Hits |", "|---|---|---|---:|"]
        for name, count in sorted(agents.items(), key=lambda kv: -kv[1]):
            info = meta.get(name, {})
            lines.append(
                f"| {name} | {info.get('vendor', '—')} | "
                f"{PURPOSE_WORD.get(info.get('purpose', ''), '—')} | {count} |"
            )
        lines.append("")
    else:
        lines += ["_Nothing archived yet._", ""]

    lines += ["## Brands looked up, all time", ""] + table(of("b"), ("Brand", "Views"))
    lines += ["## Compared against each other, all time", ""] + table(
        of("m"), ("Pair", "Times")
    )
    lines += ["## Pages, all time", ""] + table(of("v"), ("Page", "Views"))
    lines += ["## Days", ""]
    for path in reversed(files):
        lines.append(f"- [[Audience {path.stem}]]")
    lines += [
        "",
        "---",
        "",
        "Live dashboard at https://unprompted.report/admin",
        "",
        "Part of [[Projects/Unprompted/MOC|Unprompted]].",
        "",
    ]

    index = out_dir / "Audience Index.md"
    if index.exists() and INDEX_STAMP not in index.read_text(encoding="utf-8"):
        print(f"skip (not ours): {index.name}", file=sys.stderr)
        return
    index.write_text("\n".join(lines), encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--vault", type=Path, default=DEFAULT_VAULT)
    parser.add_argument(
        "--days",
        type=int,
        default=90,
        help="how far back to pull from Redis (it keeps 90)",
    )
    args = parser.parse_args()

    if not args.vault.is_dir():
        print(f"no vault at {args.vault}", file=sys.stderr)
        return 1

    load_local_env()
    import os

    url = (os.environ.get("KV_REST_API_URL") or "").rstrip("/")
    token = os.environ.get("KV_REST_API_TOKEN") or ""
    if not url or not token:
        print(
            "KV_REST_API_URL and KV_REST_API_TOKEN are not set, so there is "
            "nothing to archive. Run `vercel env pull`.",
            file=sys.stderr,
        )
        return 1

    out_dir = args.vault / FOLDER
    out_dir.mkdir(parents=True, exist_ok=True)
    meta = registry()

    today = date.today()
    fresh = 0
    for offset in range(args.days):
        day = (today - timedelta(days=offset)).isoformat()
        counters = fetch_day(url, token, day)
        if not counters:
            continue
        if write_raw(out_dir, day, counters):
            fresh += 1

    # Notes are rebuilt from the archive rather than from Redis, so a day that
    # has aged out of the cache still renders from what was captured.
    written = 0
    for path in sorted((out_dir / "data").glob("*.json")):
        day = path.stem
        try:
            counters = json.loads(path.read_text(encoding="utf-8"))
        except ValueError:
            continue
        dest = out_dir / f"Audience {day}.md"
        body = day_note(day, counters, meta)
        if dest.exists():
            existing = dest.read_text(encoding="utf-8")
            if STAMP not in existing:
                print(f"skip (not ours): {dest.name}", file=sys.stderr)
                continue
            if existing == body:
                continue
        dest.write_text(body, encoding="utf-8")
        written += 1

    write_index(out_dir, meta)
    print(f"{fresh} day(s) archived, {written} note(s) written to {out_dir}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
