"""Copy the weekly notes into the Obsidian vault.

The measurement runs in the cloud, so the vault cannot be written by the run
itself. This pulls whatever the cloud published and mirrors the readable notes
into the vault, which is the archive that outlives the repository.

Safe to run any number of times: it only writes files it generated (identified
by their `type: unprompted-week` frontmatter) and never deletes anything.

    python scripts/sync_vault.py [--vault PATH] [--no-pull]
"""

from __future__ import annotations

import argparse
import subprocess
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
DEFAULT_VAULT = Path.home() / "FenrirVault"
FOLDER = Path("Projects") / "Unprompted" / "Weeks"
STAMP = "type: unprompted-week"


def pretty(slug: str) -> str:
    return " ".join(
        word.upper() if word in {"ai", "seo"} else word.capitalize()
        for word in slug.split("-")
    )


def pull() -> None:
    """Fast-forward only. A dirty or diverged repo is a human's problem."""
    result = subprocess.run(
        ["git", "pull", "--ff-only"],
        cwd=REPO,
        capture_output=True,
        text=True,
    )
    print(result.stdout.strip() or result.stderr.strip())
    if result.returncode != 0:
        print("pull failed, syncing whatever is already local", file=sys.stderr)


def sync(vault: Path) -> list[Path]:
    out_dir = vault / FOLDER
    out_dir.mkdir(parents=True, exist_ok=True)
    written: list[Path] = []

    for src in sorted((REPO / "reports").glob("*/*.md")):
        date = src.parent.name
        slug = src.stem
        dest = out_dir / f"{date} {pretty(slug)}.md"

        body = src.read_text(encoding="utf-8")
        # Link the note back into the graph. Wikilinks are the vault's own
        # connective tissue and are meaningless in the repo, so they are added
        # here rather than baked into the published report.
        body = body.rstrip() + (
            f"\n\nPart of [[Projects/Unprompted/MOC|Unprompted]].\n"
        )

        if dest.exists():
            existing = dest.read_text(encoding="utf-8")
            if STAMP not in existing:
                print(f"skip (not ours): {dest.name}", file=sys.stderr)
                continue
            if existing == body:
                continue

        dest.write_text(body, encoding="utf-8")
        written.append(dest)
        print(f"wrote {dest.relative_to(vault)}")

    write_index(out_dir, vault)
    return written


def write_index(out_dir: Path, vault: Path) -> None:
    """A dated list of every week, newest first."""
    notes = sorted(
        (p for p in out_dir.glob("*.md") if p.name != "Weeks Index.md"),
        reverse=True,
    )
    lines = [
        "---",
        "type: index",
        "---",
        "",
        "# Unprompted, weekly results",
        "",
        "Every measured week, newest first. Generated by `scripts/sync_vault.py`",
        "in the Unprompted repository. Edits here are overwritten.",
        "",
    ]
    for note in notes:
        lines.append(f"- [[{note.stem}]]")
    lines += [
        "",
        "---",
        "",
        "Live charts at https://unprompted.report",
        "",
        "Part of [[Projects/Unprompted/MOC|Unprompted]].",
        "",
    ]
    (out_dir / "Weeks Index.md").write_text("\n".join(lines), encoding="utf-8")


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--vault", type=Path, default=DEFAULT_VAULT)
    parser.add_argument("--no-pull", action="store_true")
    args = parser.parse_args()

    if not args.vault.is_dir():
        print(f"no vault at {args.vault}", file=sys.stderr)
        return 1

    if not args.no_pull:
        pull()

    written = sync(args.vault)
    print(f"{len(written)} note(s) updated")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
